# Generated by Django 3.2.8 on 2022-03-10 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISP_warehouse', '0004_auto_20220310_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 10, 59, 59, 122212)),
        ),
        migrations.AlterField(
            model_name='type',
            name='image',
            field=models.ImageField(default='./images/noimg.png', null=True, upload_to=''),
        ),
    ]
