# Generated by Django 3.2.8 on 2022-03-10 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISP_warehouse', '0005_auto_20220310_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='document',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 11, 6, 6, 783549)),
        ),
        migrations.AlterField(
            model_name='operation',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='image',
            field=models.ImageField(blank=True, default='./images/noimg.png', null=True, upload_to=''),
        ),
    ]
