# Generated by Django 3.2.8 on 2022-03-11 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISP_warehouse', '0010_auto_20220310_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='serial_num',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='loctype',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 14, 12, 4, 573946)),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
