# Generated by Django 3.2.8 on 2022-03-11 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISP_warehouse', '0011_auto_20220311_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='director',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='web',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 14, 28, 4, 262340)),
        ),
    ]
