# Generated by Django 3.2.8 on 2022-03-11 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISP_warehouse', '0012_auto_20220311_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='type',
            new_name='inv_type',
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 15, 11, 27, 908433)),
        ),
    ]
