# Generated by Django 3.2.8 on 2022-04-19 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISP_warehouse', '0013_auto_20220311_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='document',
            field=models.FileField(blank=True, default=None, null=True, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 11, 24, 9, 412471)),
        ),
    ]
