# Generated by Django 3.2.8 on 2022-04-19 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISP_warehouse', '0014_auto_20220419_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='document',
            field=models.FileField(blank=True, default='---', null=True, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='image',
            field=models.ImageField(blank=True, default='pictures/noimg.png', null=True, upload_to='pictures/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 15, 7, 45, 447711)),
        ),
    ]
