# Generated by Django 3.2.8 on 2022-04-27 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISP_warehouse', '0017_auto_20220420_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 17, 18, 6, 655408)),
        ),
    ]
